version: '3'
services: 
    affichage: 
        build: ./services/affichage
        ports: 
            - "3000:3000"
        depends_on: 
            - database
        restart: on-failure
    ajout:
        build: ./services/ajout
        ports: 
            - "4000:4000"
        depends_on: 
            - database
        restart: on-failure
    database:
        image: mysql
        build: ./services/database
        ports: 
            - 3306:3306
        environment: 
             MYSQL_DATABASE: base
             MYSQL_PASSWORD: 
             MYSQL_USER: root
             MYSQL_ROOT_PASSWORD: password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - 8080:80 
        environment:
             MYSQL_PASSWORD: 
             MYSQL_USER: root
             MYSQL_ROOT_PASSWORD: password 